//  -------------------------------------------------------------
//  Question 1:   Syntax error
//  -------------------------------------------------------------
//  The program below is designed to get the name of the user
//	and then display a welcome message.
//	
//  When compiling the program a number of syntax errors are 
//  generated by the compiler. Correct these errors so that the
//  program can produce the expected output shown below:
//
//  Sample Run 1:
//   
//      Enter your name: Benny
//		
//		Hello Benny!
//
//  Sample Run 2:
//  
//      Enter your name: Kate
//		
//		Hello Kate!
//
//  -------------------------------------------------------------

#include <iostream> 
using namespace std

int main()
{
	string name;

	cout << "Enter your name: "; 
	cin  << name;
	cout << "Hello  " << name << '!\n';

	return 0;
}
